server:
  port: 8080
  timeout: 30
  bodyLimit: 10
  allowOrigins: ['*']

database:
  host: ""  # Will be set from DATABASE_HOST
  port: 0     # Will be set from DATABASE_PORT
  dbname: "" # Will be set from DATABASE_DBNAME
  user: ""   # Will be set from DATABASE_USER
  password: "" # Will be set from DATABASE_PASSWORD
  sslmode: "" # Will be set from DATABASE_SSLMODE
