server:
  port: 8000
  allowOrigins:
    - 'http://localhost:3000'
  bodyLimit: 10 #mb
  timeout: 30 #second

database:
  host: 'localhost'
  port: 5432
  user: 'postgres'
  password: 'postgres'
  dbname: 'dbname'
  sslmode: 'disable'
  schema: 'public'
