definitions:
  model.LoginResponse:
    properties:
      token:
        type: string
    type: object
  model.LoginWithPasswordRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.LoginWithPinRequest:
    properties:
      pin:
        type: integer
      username:
        type: string
    type: object
  model.NewPINRequest:
    properties:
      pin:
        type: integer
    type: object
  model.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.UserResponse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login a user with password
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LoginWithPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResponse'
      summary: Login with password
      tags:
      - Authentication
  /v1/auth/login-with-pin:
    post:
      consumes:
      - application/json
      description: Login a user with pin
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LoginWithPinRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResponse'
      summary: Login with pin
      tags:
      - Authentication
  /v1/auth/new-pin/{id}:
    post:
      consumes:
      - application/json
      description: Create a new PIN for a user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: New PIN object
        in: body
        name: pin
        required: true
        schema:
          $ref: '#/definitions/model.NewPINRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.UserResponse'
      summary: New PIN
      tags:
      - Authentication
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.UserResponse'
      summary: Register user
      tags:
      - Authentication
  /v1/users:
    get:
      consumes:
      - application/json
      description: List all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserResponse'
            type: array
      summary: List users
      tags:
      - User
  /v1/users/{id}:
    get:
      consumes:
      - application/json
      description: Read a specific user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserResponse'
      summary: Read user
      tags:
      - User
swagger: "2.0"
